import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import { globalCss } from '@pigment-css/react';

globalCss`
  body {
    margin: 0;
  }
`;

const inter = Inter({
  subsets: ['latin'],
  style: ['normal', 'italic'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Electric & Press",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
